config:
  info: "master branch,config-repo config-dev.yml version=8"
  
spring:
  application:
    name: order
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
